# Generated by Django 3.0.3 on 2020-02-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='quizzes.Question')),
            ],
            options={
                'ordering': ('score',),
            },
        ),
        migrations.CreateModel(
            name='Taken_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('questions', models.ManyToManyField(related_name='Taken_Test', through='users.Score', to='quizzes.Question')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Taken_Test', to='quizzes.Test')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='score',
            name='taken_test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='users.Taken_Test'),
        ),
    ]
